infra: add make install and greeting

diff --git a/kernel/Makefile b/kernel/Makefile
--- a/kernel/Makefile
+++ b/kernel/Makefile
@@ -12,12 +12,23 @@ ifneq ($(KERNELRELEASE),)
 include Kbuild
 
 else
-
 # out-of-tree-build process
+
+MARSSRC := $(shell pwd)
+DESTDIR ?= /
 KDIR ?= /lib/modules/`uname -r`/build
 
-default:
+.PHONY: greeting install default clean config
+
+default: greeting 
 	$(MAKE) -C $(KDIR) M=$(PWD)
+
+greeting:
+	@echo "Building MARS Module again: KDIR=$(KDIR)" ;
+	@if ! test -e $(KDIR)/Makefile ; then \
+		echo -e "Sorry, kernel makefile not found. You need to tell me a correct KDIR!\n" ; \
+		false; \
+	fi
 
 clean:
 	$(MAKE) -C $(KDIR) M=$(PWD) clean
@@ -25,4 +36,6 @@ clean:
 config:
 	$(MAKE) -C $(KDIR) M=$(PWD) config
 
+install:
+	$(MAKE) -C $(KDIR) M=$(PWD) modules_install
 endif
